### ISSUE TITLE
[BUG] CSS 이슈

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-front#35]
## Describe the bug 🐞
CSS 마이 페이지 루트에 안 쓰는 div태그 하나 들어가 있어서 아래 자식 요소들에 css 적용 여부(중앙 정렬 등)가 불투명해집니다. div 확인해보고 안 쓰는 태그면 삭제해주세요.

```
export default function MyPageMain() {
  return (
    <>
      //<div> //이 div태그
        <MyPageMenuBar />
        <Outlet />
      </div>
    </>
  );
}
```

## Page 🖥️
 MyPageMain

**Comment by 7memoria7** [comment]
div 가 있어서 중앙정렬이 불투명해진다는 말이 정확하게 어떤 의미인지 모르겠습니다.
아래 자식요소들의 css에 중앙정렬이 가능합니다. 다시확인해주세요.
지금 사용하지 않는 div는 삭제하겠습니다.

**Comment by fkthfvk112** [comment]
ex)
```
<div>//flex로 자식 요소 가운데 중앙 정렬 - 1)
    <div> //안쓰는 div  - 2)
         <div> //중앙 정렬 되어야할 div 요소들 - 3)
```
위 같이 구성 될 경우, 세 번째 div는 두 번째 안 쓰는 div의 앞쪽부터 정렬(2번 div가 width 100%이며 블록을 차지하게 설정된 경우 - 세 번째 div는 두 번째 div의 자식이기에) 될 것입니다. 실제로 flex로 중앙 정렬 되어야 할 div는 3번째 태그인데도 말이죠. css를 확인하니 두 번째 div는 쓰지 않는 것이 확인되었고, 그렇다면 세 번째 div가 직접적으로 flex의 자식 요소로 오는 것이 명확하다고 판단해서 "불투명하다"라는 표현을 한 것입니다.
